version: '3'
services:
  prometheus:
      image: prom/prometheus
      container_name: prometheus
      ports:
        - 9090:9090
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
      command:
        - '--web.enable-remote-write-receiver'
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'

  #http://localhost:9090/targets?search=
  #http://localhost:9090/metrics

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
      - PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR=true
      - PROMETHEUS_QUERY_NAMESPACE=span_metrics
      - PROMETHEUS_QUERY_DURATION_UNIT=s


  otel-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: otel-collector
    platform: linux
    environment:
      - TZ=GMT+0    
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "31888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "55679:55679" # zpages extension
      
    depends_on:
      - jaeger-all-in-one
      - prometheus

  api_1:
    hostname: api_1
    container_name: api_1
    build: .
    ports:
      - "3535:3535"
    restart: always
    environment:
      - PORT=3535
      - METRIC=http://otel-collector:4318/v1/metrics
      - TRACE=http://otel-collector:4318/v1/traces
      - OTEL_EXPORTER_OTLP_ENDPOINT="http://otel-collector:4318"

# https://www.jaegertracing.io/docs/1.46/getting-started/
# https://logz.io/blog/nodejs-javascript-opentelemetry-auto-instrumentation/#tracer
# https://github.com/aspecto-io/opentelemetry-bootcamp/blob/master/src/tracer.ts
# https://github.com/open-telemetry/opentelemetry-js/blob/main/examples/otlp-exporter-node/tracing.js
# https://opentelemetry.io/docs/collector/getting-started/
# https://opentelemetry.io/docs/collector/configuration/
# https://github.com/open-telemetry/opentelemetry-erlang/blob/main/config/otel-collector-config.yaml
# https://medium.com/@guilospanck/telemetry-with-opentelemetry-prometheus-and-jaeger-46a2d9dec86b
# https://github.com/SumoLogic/sumologic-otel-collector