# https://github.com/open-telemetry/opentelemetry-erlang/blob/main/config/otel-collector-config.yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

connectors:
  spanmetrics:
    namespace: span.metrics

processors:
  batch:
  spanmetrics:
    metrics_exporter: prometheus

exporters:
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"

  # splunk_hec:
  #   token: "00000000-0000-0000-0000-0000000000000"
  #   endpoint: "https://splunk:8088/services/collector"
  #   index: "logs"
  #   tls:
  #     insecure_skip_verify: true

  logging:
    loglevel: info

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [ batch, spanmetrics ]
      # exporters: [logging, jaeger, spanmetrics]
      exporters: [jaeger, spanmetrics]
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [batch]
      # exporters: [logging, prometheus]
      exporters: [prometheus]
    # logs:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [logging, splunk_hec]


#USAR FILELOG
#https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/filelogreceiver